package com.empanak.dmojutils.view;

import com.empanak.dmojutils.common.OnContestSelectedListener;
import com.empanak.dmojutils.dmojDTO.contestList.ContestData;
import com.empanak.dmojutils.repository.ContestRepository;
import com.empanak.dmojutils.view.component.ContestPanel;

import javax.swing.*;
import java.awt.*;
import java.time.Instant;

public class ContestWindow extends  JFrame {

    private ContestPanel contestController;
    private final ContestRepository contestRepository;
    private final OnContestSelectedListener listener;
    private JPanel contestPanel;

    public ContestWindow(ContestRepository contestRepository, OnContestSelectedListener listener) {
        this.contestRepository = contestRepository;
        this.listener = listener;
        $$$setupUI$$$();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setMinimumSize(new Dimension(500, 300));
        setSize(500, 300);
        setLocationRelativeTo(null);
        setContentPane(contestPanel);
        pack();
        setVisible(true);
        setTitle("Añadir concurso a seguimiento");
        initComponents();
    }

    private void initComponents() {
        contestController.loadContests();
        contestController.setOnContestTableChange(()->{
            dispose();
            ContestData contestData = contestController.getContestList().get(contestController.getSelectedContest()).getLeft();
            if(Instant.now().isAfter(contestData.end_time) || Instant.now().isBefore(contestData.start_time)){
                JOptionPane.showMessageDialog(this, "El concurso no esta en curso", "Concurso inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
            listener.onContestSelected(contestController.getSelectedContest());

        });
    }

    private void createUIComponents() {
        contestController = new ContestPanel(contestRepository, false);
        contestPanel = new JPanel();
        contestPanel.add(contestController.getRootPanel(), BorderLayout.CENTER);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contestPanel;
    }
}
