package com.empanak.dmojutils.view.component;

import lombok.Getter;
import org.apache.commons.lang3.tuple.Pair;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class ResultsPanel {
    private JTable resultsTable;
    @Getter
    private JPanel rootPanel;
    private DefaultTableModel resultsTableModel;

    public ResultsPanel() {
        $$$setupUI$$$();
        initComponents();
    }

    private void initComponents() {

    }

    private void createUIComponents() {
        String[] resultColumns = {"Pos", "User", "Puntos", "Tiempo"};
        resultsTableModel = new DefaultTableModel(resultColumns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        resultsTable = new JTable(resultsTableModel);

        resultsTable.getTableHeader().setReorderingAllowed(false);
        resultsTable.setRowHeight(25);
        resultsTable.getColumnModel().getColumn(0).setMaxWidth(50);
    }

    public void clearTable() {
        resultsTableModel.setRowCount(0);
    }

    public void showRank(List<Map.Entry<String, Pair<Integer, Long>>> rankList, Set<String> excludedUsers) {
        clearTable();
        int pos = 1;
        for (Map.Entry<String, Pair<Integer, Long>> entry : rankList) {
            if (!excludedUsers.contains(entry.getKey())) {
                resultsTableModel.addRow(new Object[]{pos, entry.getKey(), entry.getValue().getLeft(), entry.getValue().getRight()});
                pos++;
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(resultsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
