package com.empanak.dmojutils.view.component;

import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.tuple.Pair;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class UsersPanel {

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 5, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBorder(BorderFactory.createTitledBorder(null, "Usuarios", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Buscar:");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        clearExclusionsBtn = new JButton();
        clearExclusionsBtn.setText("Limpiar exclusiones");
        rootPanel.add(clearExclusionsBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(userTable);
        addUserBtn = new JButton();
        addUserBtn.setText("+");
        rootPanel.add(addUserBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeUserBtn = new JButton();
        removeUserBtn.setText("-");
        rootPanel.add(removeUserBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUserFilter = new JTextField();
        rootPanel.add(txtUserFilter, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    public enum UsersMode {
        ALL, ONLY_PARTICIPANTS
    }

    private JTextField txtUserFilter;
    private JTable userTable;
    private JButton clearExclusionsBtn;
    @Getter
    private JPanel rootPanel;
    private JButton addUserBtn;
    private JButton removeUserBtn;
    private DefaultTableModel userTableModel;
    private TableRowSorter<DefaultTableModel> sorter;
    @Getter
    private String selectedUser;
    @Setter
    private Runnable onUserTableChange;
    @Setter
    private Runnable onUserTableSelection;

    @Getter
    private Set<String> excludedUsers = new HashSet<>();
    private boolean clearingExclusions = false;

    public UsersPanel(UsersMode usersMode) {
        $$$setupUI$$$();
        if (usersMode == UsersMode.ONLY_PARTICIPANTS) {
            addUserBtn.setVisible(false);
            removeUserBtn.setVisible(false);
        }
        initComponents();
    }

    private void initComponents() {
        userTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (column != 0) return;
            if ((Boolean) userTableModel.getValueAt(row, column)) {
                excludedUsers.remove((String) userTableModel.getValueAt(row, 1));
            } else {
                excludedUsers.add((String) userTableModel.getValueAt(row, 1));
            }
            if (clearingExclusions) return;
            onUserTableChange.run();
        });

        userTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(userTable.columnAtPoint(e.getPoint()) == 0) return; // Si se hace click en la columna de exclusión
                selectedUser = (String) userTable.getValueAt(userTable.rowAtPoint(e.getPoint()), 1);
                if(onUserTableSelection != null)
                    onUserTableSelection.run();
            }
        });

        clearExclusionsBtn.addActionListener(e -> {
            clearingExclusions = true;
            for (int i = 0; i < userTable.getRowCount(); i++) {
                userTable.setValueAt(true, i, 0);
            }
            clearingExclusions = false;
            onUserTableChange.run();
        });

        txtUserFilter.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filter();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filter();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filter();
            }
        });
    }

    private void createUIComponents() {
        String[] userColumns = {"X", "User"};
        userTableModel = new DefaultTableModel(userColumns, 0) {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 0) {
                    return Boolean.class;
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0;
            }
        };

        userTable = new JTable(userTableModel) {
            @Override
            public String getToolTipText(MouseEvent e) {
                int row = rowAtPoint(e.getPoint());
                int column = columnAtPoint(e.getPoint());
                Object value = getValueAt(row, column);
                return value != null ? value.toString() : null;
            }
        };

        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.setRowHeight(25);
        userTable.getColumnModel().getColumn(0).setMaxWidth(30);

        sorter = new TableRowSorter<>(userTableModel);
        userTable.setRowSorter(sorter);
    }

    public void filter() {
        String filter = txtUserFilter.getText();
        if (filter.trim().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, 1));
        }
    }

    public void updateUsersList(List<Map.Entry<String, Pair<Integer, Long>>> rankList) {
        while (userTable.getRowCount() > 0) {
            userTableModel.removeRow(0);
        }
        if (rankList == null) return;
        System.out.println("Actualizando con " + rankList.size() + " usuarios");
        for (Map.Entry<String, Pair<Integer, Long>> entry : rankList) {
            userTableModel.addRow(new Object[]{!excludedUsers.contains(entry.getKey()), entry.getKey()});
        }
    }

    public int getExcludedUsersCount() {
        return excludedUsers.size();
    }
}
